name: Workflow

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #-name: dependencies
    #run: |
    #   apt-get install gcc
    #   não é necessário, pois "ubunto-latest" já vem com o compilador
    - name: ContaCompile
      run: | 
        g++ -std=c++11 contaBanco.cpp -o contaBanco.o -c 
    - name: MainCompile
      run: |
        g++ -std=c++11 main.cpp -o main.o -c
    - name: link
      run: |
        g++ main.o contaBanco.o
